version: '3'

services:
    ngx:
        container_name: ngx
        image: ngx
        build:
            context: .
            dockerfile: ./docker/${DOCKER_RUNTIME-php-ngx}/Dockerfile
        ports:
            - ${DOCKER_EXPOSE_PORT-8000}:8000
        env_file:
            - .env
        volumes:
            - ./:/app
