version: '3'

services:
    laravel_octane:
        container_name: laravel-${DOCKER_RUNTIME-php-ngx}
        image: laravel-${DOCKER_RUNTIME-php-ngx}
        build:
            context: .
            dockerfile: ./docker/${DOCKER_RUNTIME-php-ngx}/Dockerfile
        ports:
            - ${DOCKER_EXPOSE_PORT-8000}:${DOCKER_SOURCE_PORT-8000}
        env_file:
            - .env
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: '1'
