version: '3'

services:
    ngx:
        container_name: ngx
        image: ngx
        build:
            context: .
            dockerfile: php-ngx.dockerfile
        ports:
            - ${APP_PORT-8000}:8000
        env_file:
            - .env
        volumes:
            - ./:/app
