version: '3'

services:
    laravel_octane:
        container_name: laravel_octane
        image: laravel_octane
        build:
            context: .
            dockerfile: ./docker/${DOCKER_RUNTIME-php-ngx}/Dockerfile
        ports:
            - ${DOCKER_EXPOSE_PORT-8000}:${DOCKER_SOURCE_PORT-8000}
        env_file:
            - .env
